name: Release

on:
  push:
    tags:
      - v*

concurrency:
  group: release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1.13'
          tools: composer

      - name: Update Dependencies
        run: composer update --no-interaction --no-progress --prefer-dist

      - name: Validate Composer Configuration
        run: composer validate

      - name: Install Dependencies and Dump Autoload
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          composer dump-autoload

      - name: Build Package
        run: composer build

      - name: Prepare Generated Files Directory
        run: |
          mkdir generated_files
          mkdir -p generated_files/Eolib/Protocol/Generated
          mkdir -p generated_files/docs
          cp -R Eolib/Protocol/Generated/* generated_files/Eolib/Protocol/Generated/
          cp -R docs/* generated_files/docs/
          cp -R vendor generated_files/vendor

      - name: Checkout Distribution Repository
        uses: actions/checkout@v4
        with:
          repository: 'ExileStudios/eolib-php-dist'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'eolib-php-dist'
          ref: 'main'

      - name: Transfer Files to Distribution Repository
        run: |
          cp -R generated_files/* eolib-php-dist/
          mkdir -p eolib-php-dist/.github/workflows
          cp .github/dist_workflows/release.yml eolib-php-dist/.github/workflows/release.yml

      - name: Commit and Push Changes
        working-directory: ./eolib-php-dist
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add .
          git commit -m "Update generated files and workflow for release ${{ github.ref_name }}"
          git push origin HEAD:main
          git tag ${{ github.ref_name }}
          git push origin ${{ github.ref_name }}

      - name: Cleanup Temporary Files
        run: rm -rf generated_files
